apiVersion: apps/v1
kind: Deployment
metadata:
  name: testkubernetes
  labels:
    app: product-app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: testkubernetes
  template:
    metadata:
      labels:
        app: product-app
        service: testkubernetes
    spec:
      containers:
        - name: testkubernetescontainer
          image: testkubernetes:dev
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: testkubernetesservice
  labels:
    app: product-app
    service: testkubernetes
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: testkubernetes